# Generated by Django 4.2 on 2025-05-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date_1', models.DateField()),
                ('payment_1', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dhara_day', models.IntegerField()),
                ('taka', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date_2', models.DateField()),
                ('payment_2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
