# Generated by Django 4.2 on 2025-05-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_date_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
