# Generated by Django 4.2 on 2025-05-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0002_alter_invoice_payment_date_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_2',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
