# Generated by Django 4.2 on 2025-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0004_alter_invoice_options_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
