# Generated by Django 4.2 on 2025-05-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0005_alter_invoice_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='settled_payment_2',
            field=models.BooleanField(default=False),
        ),
    ]
