# Generated by Django 4.2 on 2025-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0006_invoice_settled_payment_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
