# Generated by Django 4.2 on 2025-05-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recorder', '0007_invoice_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date_1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
